title: í¬ì›ì´ì˜ í¬í´ ì‚¬ì´íŠ¸
name: ì‹ í¬ì›
email: shw20231@gmail.com
description: >-
  Front-End DEVELOPER


baseurl: ""
url: "https://shinheewon01.github.io"


# profile ì´ë¯¸ì§€
profile_image: images/me.png


# SNS ì•„ì´ë””
GitHub_id: "https://github.com/shinheewon01"
Notion_id: babycheetah
Study_id: babycheetah


# # Youtube vid
# youtube_vid: #


# Custom Color 
primary: 1a31a1  #b72cf0 #ì „ì²´ì ì¸ ìƒ‰ìƒ
primary_hover: 0f943a #9a2dc7 # í˜¸ë²„ ìƒ‰ìƒ
color_1: ec5453 #ë¹¨ê°• #b72cf0 # Tech  skill ec5453
color_2: f9bf3f #ë…¸ë‘
color_3: 2c98f0 #íŒŒë‘
color_4: 0f943a #ì´ˆë¡   #a84cb8(ë³´ë¼)
color_5: 2fa499
color_6: 4054b2


# slider type 0  (í…ìŠ¤íŠ¸ê°€ ìš°ì¸¡ ì •ë ¬ëœ ìŠ¬ë¼ì´ë”)
slider_0: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/img_bg.jpg
  title: Hewon's <br> Portfoilo!</br> Site
  position: absolute
  transform: translate(-50%, -50%)
  left: 200px
  bottom: 80px


# slider type 1  (í…ìŠ¤íŠ¸ê°€ ì¢Œì¸¡ ì •ë ¬ëœ ìŠ¬ë¼ì´ë”)
slider_1: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/img_bg2.jpg
  title: I am<br>Front End Developer
  subtitle: >- 
    "ì•ˆë…•í•˜ì„¸ìš”ğŸ‘‹ ì‹ ì… Front-End ê°œë°œì<br> <strong>ì‹ í¬ì›</strong>ì…ë‹ˆë‹¤ (à¸‡Ë™âˆ‡Ë™)à¸§â€
  position: absolute
  transform: translate(-50%, -50%)
  left: 200px
  bottom: 280px


# About
about_meta: About Me
about_header: >- 
  "ë…¸ë ¥í•˜ëŠ” ì‚¬ëŒ, ê¿ˆì„ ì«“ëŠ” ì‚¬ëŒ"
about_introduce: >-
  "ì•ˆë…•í•˜ì„¸ìš”. Frond-End ì „ë¬¸ê°€ë¥¼ ê¿ˆê¾¸ëŠ” ì‹ í¬ì› ì…ë‹ˆë‹¤."
about_content: >-
  í•™ì°½ì‹œì ˆ ì»´í“¨í„°ë¥¼ ì¢‹ì•„í•˜ëŠ” ë§ˆìŒê³¼ ë¬´ì–¸ê°€ë¥¼ ë§Œë“œëŠ” ê²ƒì„ ì¢‹ì•„í•˜ê³  ê¿ˆê¿”ì™”ìŠµë‹ˆë‹¤.<br>
  ì œê°€ ìŠ¤ìŠ¤ë¡œ ë§Œë“¤ê³  ì¸ì •ë°›ëŠ” ê²ƒì„ ì¢‹ì•„í–ˆìŠµë‹ˆë‹¤.<br>
  ê·¸ë¦¬í•˜ì—¬ ì»´í“¨í„°ì†Œí”„íŠ¸ì›¨ì–´ê³µí•™ê³¼ë¡œ ì§„í•™ì„ í•˜ì˜€ìŠµë‹ˆë‹¤. <br>
  ê·¸ëŸ¬ë‚˜ ëŒ€í•™ì—ì„œ ë°°ìš°ëŠ” ê²ƒì€ ì œê°€ ìƒê°í•œ ê²ƒê³¼ ë‹¤ë¥´ê²Œ ì´í•´í•˜ê¸°ì— ì–´ë ¤ì›€ì´ ìˆì—ˆìœ¼ë©° <br>
  ì²˜ìŒ í•˜ëŠ” í”„ë¡œì íŠ¸ì— ëŒ€í•´ ì ì‘ í•˜ì§€ ëª»í•œ ë¶€ë¶„ì´ ìˆì–´ ì „ê³¼ ìƒê°ì„ ê°€ì§€ê³  ìˆì—ˆìŠµë‹ˆë‹¤. <br>
  ê·¸ëŸ¬ë‚˜ 3í•™ë…„ë•Œ ì›¹í”„ë¡œê·¸ë˜ë° ìˆ˜ì—…ì„ ë“¤ì€ í›„ ì•„ì´ë””ì–´ë¥¼ ë°˜ì˜í•˜ì—¬<br> ì›¹í˜ì´ì§€ê°€ ì œì‘ë˜ëŠ”ê²ƒì— í¥ë¯¸ë¥¼ ëŠê»´ ë”ìš± ë” í”„ë¡œì íŠ¸ë¥¼ ì—´ì‹¬íˆ ì œì‘í•˜ì˜€ìŠµë‹ˆë‹¤.<br>
  ê·¸ ì´í›„ ì €ëŠ” Front-End ê°œë°œìê°€ ë˜ê³  ì‹¶ë‹¤ëŠ” ê¿ˆì„ ê°€ì§€ê²Œ ë˜ì—ˆìŠµë‹ˆë‹¤.<br>
  <strong>ì•„ì§ ëª¨ë¥´ëŠ”ê²ƒ íˆ¬ì„±ì´ê³  ë¶€ì¡±í•¨ì´ ìˆì„ ìˆ˜ ìˆì§€ë§Œ ë” í¬ê¸°í•˜ì§€ ì•Šê³  ë…¸ë ¥í•˜ë©° ë°°ì›Œ ë‚˜ê°€ê³  ìˆìŠµë‹ˆë‹¤</strong><br>
  ê°ì‚¬í•©ë‹ˆë‹¤.
about_services: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- icon: icon-data
  name: React
- icon: icon-monitor
  name: Vue.js
- icon: icon-phone3
  name: HTML
- icon: icon-code
  name: Github

about_box_content: 
 <strong>'ì„±ê³µí•œ ì‚¬ëŒì´ ì•„ë‹ˆë¼ ê°€ì¹˜ ìˆëŠ” ì‚¬ëŒì´ ë˜ê¸° ìœ„í•´ í˜ì“°ë¼.'</strong> <br>
  ë¼ëŠ” ë§ì´ ìˆìŠµë‹ˆë‹¤. <br>
  <br>
  ê°€ì¹˜ ìˆëŠ” ì‚¬ëŒ ì¦‰ ë…¸ë ¥ í•˜ëŠ” ì‚¬ëŒì„ ì´ê¸¸ ìˆ˜ ìˆëŠ” ìëŠ” ì—†ìŠµë‹ˆë‹¤. <br>

about_box_content_color: rgb(255,255,255)
  
about_box_button:
  link: https://github.com/shinheewon01
  name: Front-Endì˜ <strong>'ê°€ì¹˜ ìˆëŠ” ì‚¬ëŒ'</strong>ì´ ë˜ê² ìŠµë‹ˆë‹¤.<br>


# Tech  skill
tech_meta: TECH SKILLS
tech_header: ì €ëŠ” í˜„ì¬ ì´ê²ƒì„ í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
tech_content: MY TECH SKILLS
tech_list: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- name: React
  color: color-1
  animation: fadeInLeft
  percent: 50
  mark: 50
  content: Reactì˜ ê¸°ì´ˆë¥¼ í™œìš©í•˜ì—¬ í”„ë¡œì íŠ¸ë¥¼ ì œì‘í•˜ê³  ì´í•´í•˜ì˜€ìŠµë‹ˆë‹¤. ê·¸ëŸ¬ë‚˜ ìì„¸í•œ ë¶€ë¶„ê¹Œì§€ ê³µë¶€ê°€ ë” í•„ìš”í•œ ë¶„ì•¼ê°™ìŠµë‹ˆë‹¤.

- name: Vue.js
  color: color-2
  animation: fadeInRight
  percent: 40
  mark: 40
  content: ê³µë¶€í•˜ê³  ê·¸ê²ƒì„ í™œìš©í•˜ì—¬ í”„ë¡œì íŠ¸ë¥¼ ì œì‘í•  ìˆ˜ë¡ ë”ìš± ë” ê³µë¶€í•´ì•¼í•˜ëŠ” ë¶„ì•¼ë¼ê³  ìƒê°í•©ë‹ˆë‹¤. ë³´ì•ˆì ì— ëŒ€í•´ ê³µë¶€í•˜ê³  ì´í•´í•˜ì—¬ í”„ë¡œì íŠ¸ì— ì ìš©í•˜ê³  ì‹¶ë‹¤ëŠ” ìƒê°ì„ í•˜ì˜€ìŠµë‹ˆë‹¤.

- name: javascript
  color: color-3
  animation: fadeInLeft
  percent: 40
  mark: 40
  content: ì¼ë°˜ javascriptì™€ëŠ” ë‹¤ë¥¸ React javascript ë¥¼ ê³µë¶€í•˜ì—¬ í”„ë¡œì íŠ¸ì— ì ìš©í•˜ì˜€ìŠµë‹ˆë‹¤. ì²˜ìŒ ë°°ìš°ë˜ ë¶„ì•¼ì™€ ë‹¤ë¥¸ ë¶„ì•¼ì—¬ì„œ ì–´ë ¤ì›€ì„ ë§ì´ ëŠê¼ˆì§€ë§Œ ë” ê³µë¶€í•˜ê³  ì‹¶ë‹¤ëŠ” ë§ˆìŒì´ ë“¤ì—ˆìŠµë‹ˆë‹¤

- name: Github
  color: color-4
  animation: fadeInRight
  percent: 50
  mark: 50
  content: ëŒ€ë¶€ë¶„ì˜ í”„ë¡œì íŠ¸ë¥¼ githubë¥¼ í†µí•´ ì†ŒìŠ¤ ì½”ë“œë¥¼ ê´€ë¦¬í•˜ì˜€ìŠµë‹ˆë‹¤. ë˜í•œ githubì„œë²„ë¥¼ í™œìš©í•˜ì—¬ í¬íŠ¸í´ë¦¬ì˜¤ ì‚¬ì´íŠ¸ë¥¼ ê´€ë¦¬í•˜ì˜€ìŠµë‹ˆë‹¤.
tech_desc: ì•ìœ¼ë¡œ ë¶€ì¡±í•œ Front-End ê³¼ Back-Endì„ ê³µë¶€í•˜ê¸° ìœ„í•´  <strong>React-Nativeì™€ jango</strong>ë“±ì„ ê³„ì†í•´ì„œ ì¡°ê¸ˆì”© ê³µë¶€í•  ìƒê°ì…ë‹ˆë‹¤.


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>ê°œì¸ í”„ë¡œì íŠ¸</span><span>íŒ€ í”„ë¡œì íŠ¸</span><span>Business</span>
project_load_more: ì•ìœ¼ë¡œ ë” ë§ì€ í”„ë¡œì íŠ¸ê°€ ì¶”ê°€ë  ì˜ˆì •ì…ë‹ˆë‹¤:)    # ë”ë³´ê¸° ë‚´ìš©
project_load_more_url: https://github.com/shinheewon01

project_my_name: ê°œì¸í”„ë¡œì íŠ¸

project_my: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/personal_project_1.png
  animation: fadeInLeft
  name: ìŠ¤íƒ€ë²…ìŠ¤ í´ë¡  ì½”ë”©
  description: ìŠ¤íƒ€ë²…ìŠ¤ í™ˆí˜ì´ì§€ë¥¼ í´ë¡ í•œ í”„ë¡œì íŠ¸ë¥¼ githubì— ì˜¬ë¦¬ê³  ë¸Œëœì¹˜ë¥¼ ìƒì„±í•˜ë©°, ë¡œê·¸ì¸ í˜ì´ì§€ë¥¼ ê°œë°œí•˜ì—¬ 'ë²„ì „ê´€ë¦¬'ë¥¼ í•˜ì˜€ìŠµë‹ˆë‹¤.<br> HTML CSS JavaScript'
  detail_url: https://zen-colden-7c5a25.netlify.app
  readmore_url: https://github.com/shinheewon01/Starbucks
- background_url: images/personal_project_2.png
  animation: fadeInLeft
  name: ì˜í™”ê²€ìƒ‰ ì‚¬ì´íŠ¸
  description: ì˜í™” ê²€ìƒ‰ APIë¥¼ ì—°ë™í•˜ê³ , Vue.js í”„ë ˆì„ ì›Œí¬ë¥¼ í™œìš©í•˜ì—¬ ê²€ìƒ‰ í˜ì´ì§€, ì¹´ë“œí˜• ì˜í™”ëª©ë¡í˜ì´ì§€, ì˜í™” ìƒì„¸ í˜ì´ì§€ë¥¼ êµ¬í˜„í–ˆìŠµë‹ˆë‹¤! <br> Vue Netlify Jest Cypress Nuxt.js Heroku 
  detail_url: https://deluxe-pothos-10f2ea.netlify.app
  readmore_url: https://github.com/shinheewon01/web-movie-app

- background_url: images/personal_project3.png
  animation: fadeInLeft
  name: ì‡¼í•‘ëª° ì‚¬ì´íŠ¸
  description: Reactë¥¼ í™œìš©í•˜ì—¬ ìƒí’ˆ ëª©ë¡ì„ ìƒì„±í•˜ê³ , ìƒí’ˆì„ ì¶”ê°€ ë° ìˆ˜ì •í•˜ë©°, ì¥ë°”êµ¬ë‹ˆ ê¸°ëŠ¥ ë“±ì´ íƒ€ì¬ëœ ì‹¤ì œ ìƒìš©í™” ê°€ëŠ¥í•œ ì‡¼í•‘ëª° ì‚¬ì´íŠ¸ë¥¼ êµ¬í˜„í•˜ì˜€ìŠµë‹ˆë‹¤. <br> React Redux Jest AWS S3 Node.js Express.js GraphQL NginX
  detail_url: https://nimble-mandazi-e59a52.netlify.app
  readmore_url: https://github.com/shinheewon01/prototype-shop

- background_url: images/personal_project4.png
  animation: fadeInLeft
  name: Todo ì‚¬ì´íŠ¸
  description: í”„ë¡ íŠ¸ì—”ë“œ í”„ë ˆì„ì›Œí¬ì¸ Svelteì˜ ê¸°ë³¸ì ì¸ ê¸°ëŠ¥ë“¤ì„ ìµí ìˆ˜ ìˆë„ë¡ APIë¥¼ ì—°ë™í•˜ì—¬ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤ <br> Svelte API 
  detail_url: https://endearing-gingersnap-6b5d2c.netlify.app
  readmore_url: https://github.com/shinheewon01/svelte-todo-app-hewon

- background_url: images/personal_project5.png
  animation: fadeInLeft
  name: ê°œì¸ ë¸”ë¡œê·¸ ì‚¬ì´íŠ¸
  description: Reactì˜ ì„œë²„ ì‚¬ì´ë“œ ë Œë”ë§ í”„ë ˆì„ì›Œí¬ì¸ Next.jsë¥¼ í™œìš©í•˜ì—¬ ì •ì  ë¸”ë¡œê·¸ë¥¼ ë§Œë“¤ì–´ë³´ê³ , ë°°í¬í•˜ì˜€ìŠµë‹ˆë‹¤. <br> Next.js ì •ì ë¸”ë¡œê·¸ 
  detail_url: https://unique-khapse-250736.netlify.app
  readmore_url: https://github.com/shinheewon01/myblog-hewon

- background_url: images/team_project1.PNG
  animation: fadeInLeft
  name: DB í¬íŠ¸í´ë¦¬ì˜¤
  description: ëŒ€í•™ ìƒí™œ ë™ì•ˆ ì§„í–‰í•œ í”„ë¡œì íŠ¸ ì¤‘ DBë¶€ë¶„ì„ ì •ë¦¬í•˜ì˜€ìŠµë‹ˆë‹¤ .
  detail_url: https://github.com/shinheewon01/ShinHewon-Portfolio
  readmore_url: pdf/SHW_Portfolio_DB.pdf

- background_url: images/team_project2.PNG
  animation: fadeInLeft
  name: ì›¹ í¬íŠ¸í´ë¦¬ì˜¤
  description: ëŒ€í•™ ìƒí™œ ë™ì•ˆ ì§„í–‰í•œ í”„ë¡œì íŠ¸ ì¤‘ WEBë¶€ë¶„ì„ ì •ë¦¬í•˜ì˜€ìŠµë‹ˆë‹¤ .
  detail_url: https://github.com/shinheewon01/ShinHewon-Portfolio
  readmore_url: pdf/SHW_Portfolio_Web.pdf



# project_team_name: íŒ€í”„ë¡œì íŠ¸
# project_team: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
# - background_url: images/team_project3.PNG
#   animation: fadeInRight
#   name: Anti-Drone_Robot(2020.05)
#   description: 2019ë…„ ë“œë¡ ê¸°ìˆ ë°œì „ì— ë”°ë¥¸ ë“œë¡ ê´€ë ¨ ì‚¬ê³ ë“¤ì´ ë§ì•„ì§€ê³  ìˆìŒì„ íŒŒì•…í•˜ê³  ê·¸ì—ë”°ë¥¸ ëŒ€ì²˜ê°€ í•„ìš”í•˜ë‹¤ê³  ìƒê° í•˜ì—¬ ì¸ê³µì§€ëŠ¥ì„ ì´ìš©í•œ Anti Drone Robot ì„ ê°œë°œí•˜ì˜€ë‹¤
#   detail_url: #
#   readmore_url: #

# - background_url: images/team_project3.PNG
#   animation: fadeInRight
#   name: sasdasdasdsadsagjghkukt(2020.05)
#   description: 2019ë…„ ë“œë¡ ê¸°ìˆ ë°œì „ì— ë”°ë¥¸ ë“œë¡ ê´€ë ¨ ì‚¬ê³ ë“¤ì´ ë§ì•„ì§€ê³  ìˆìŒì„ íŒŒì•…í•˜ê³  ê·¸ì—ë”°ë¥¸ ëŒ€ì²˜ê°€ í•„ìš”í•˜ë‹¤ê³  ìƒê° í•˜ì—¬ ì¸ê³µì§€ëŠ¥ì„ ì´ìš©í•œ Anti Drone Robot ì„ ê°œë°œí•˜ì˜€ë‹¤
#   detail_url: #
#   readmore_url: #

# project_business_name: Business
# project_business: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
# - background_url: images/my_business.PNG
#   animation: fadeInTop
#   name: ì¸í”„ëŸ°ê°•ì˜(2021~)
#   description: >-
#     ì·¨ì¤€ê³¼ ëŒ€í•™ì›ì§„í•™ì„ ë™ì‹œì— í–ˆì„ë•Œ ë§ì€ ê³³ì—ì„œ github ì£¼ì†Œë¿ë§Œì•„ë‹ˆë¼ ê°œë°œ ë¸”ë¡œê·¸ì£¼ì†Œë„ ìš”ì²­í•˜ëŠ”ë°ê°€ ë§ì•˜ë‹¤.(ë¬¼ë¡  í•„ìˆ˜ëŠ” ì•„ë‹ˆì˜€ì§€ë§Œ) 
#     ë˜í•œ êµìœ¡ê¸°ê´€(ë©‹ìŸì´ì‚¬ìì²˜ëŸ¼,ë„¤ì´ë²„ ë¶€ìŠ¤íŠ¸ ìº í”„, ì†Œë§ˆë“±)ì—ì„œë„ ë§ˆì°¬ê°€ì§€ì´ë‹¤. í˜„ì¬ í”„ë¡œê·¸ë˜ë°ì˜ ì¤‘ìš”ë„ê°€ ì˜¬ë¼ê°€ê³ ìˆìœ¼ë©° ì´ˆë“±í•™ìƒë¶€í„° ì˜ë¬´êµìœ¡ì„ ì‹œì‘í•œë‹¤ê³  í•œë‹¤. 
#     ë§ì€ ë¹„ì „ê³µìë“¤ì´ ë’¤ëŠ¦ê²Œ í”„ë¡œê·¸ë˜ë°ì„ ì‹œì‘í•˜ê³  ìˆë‹¤. ì—´ì‹¬íˆ ë°°ìš°ê³  ì§€ì›í• ë ¤ë‹ˆ ê°œë°œ ë¸”ë¡œê·¸ë¥¼ ìš”ì²­í•œë‹¤... í”„ë¡œê·¸ë˜ë°ì„ ì‹œì‘í• ë•Œ ì•Œì•˜ë‹¤ë©´ ì–¼ë§ˆë‚˜ ì¢‹ì•˜ì„ê¹Œ. 
#     ê³µë¶€í•˜ë©´ì„œ ë¸”ë¡œê·¸ ë‚´ìš©ì„ ì±„ì› ìœ¼ë©´ ì°¸ ì¢‹ì•˜ì„ê²ƒì´ë‹¤. ì´ëŸ° íë¦„ì„ ìºì¹˜í•˜ì—¬ ë‚˜ëŠ” ê°œë°œìë‹¤ìš´ ë¸”ë¡œê·¸ì¸ ê¹ƒí—™ë¸”ë¡œê·¸ë¥¼ ë§Œë“œëŠ” ì§§ì€ ê°•ì˜ë¥¼ ë§Œë“¤ì—ˆë‹¤. 
#   detail_url: #
#   readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: ì €ëŠ” ì´ëŸ° "ê²½í—˜"ë“¤ì„ í•´ë´¤ìŠµë‹ˆë‹¤.
exp_content: í˜„ì¬ ê°œë°œë¡œì„œëŠ” í° ë„ì›€ì€ ë˜ì§€ ì•Šì„ ìˆ˜ ìˆì§€ë§Œ, íšŒì‚¬ì—ì„œ í•„ìš”ë¡œ í•œë‹¤ë©´ ì´ëŸ° ì—­ëŸ‰ë„ ê°€ì§€ê³  ìˆìŠµë‹ˆë‹¤.
exp_services: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- name: ë§¤ë‹ˆì§€ë¨¼íŠ¸
  color: color-1
  icon: icon-bulb
  content: ìŠ¤ìŠ¤ë¡œ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ì˜€ìœ¼ë©° êµë‚´ í”„ë¡œì íŠ¸ì—ì„œ ë¶„ë‹´ë°›ì€ ì—…ë¬´ë¥¼ ì„±ì‹¤íˆ ìˆ˜í–‰í•˜ì˜€ê³  íŒ€ì¥ì„ ë§¡ì€ í”„ë¡œì íŠ¸ì—ì„œëŠ” íŒ€ì›ë“¤ì˜ ëŠ¥ë ¥ì— ë§ê²Œ ì—…ë¬´ë¥¼ ë°°ì •í•˜ê³  ê´€ë¦¬í•˜ì˜€ìŠµë‹ˆë‹¤.
- name: ê¸°ìˆ ìŠµë“
  color: color-2
  icon: icon-home
  content: ì œê°€ ì„ íƒí•œ Front-Endì— ëŒ€í•´ ì—´ì •ì„ ê°–ê³  ê³µë¶€í•˜ë©° ìƒˆë¡œìš´ ê¸°ìˆ ì„ ë°°ìš°ëŠ” ê²ƒì— ë‘ë ¤ì›€ì„ ëŠë¼ì§€ ì•Šê³  ì¦ê±°ìš´ ë§ˆìŒìœ¼ë¡œ ë°°ìš°ë©° ê·¸ê²ƒì„ í™œìš©í•˜ê³ ì‹¶ìŠµë‹ˆë‹¤.
- name: ì˜í™”ê²€ìƒ‰ ì‚¬ì´íŠ¸
  color: color-3
  icon: icon-phone3
  content: API ë¥¼ ì‚¬ìš©í•œ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•´ë³´ì•˜ìœ¼ë‚˜ Vue.jsë¼ëŠ” í”„ë ˆì„ì›Œí¬ë¥¼ ì²˜ìŒ ì‚¬ìš©í•˜ì˜€ê¸°ì— ì–´ë ¤ì›€ê³¼ ë‘ë ¤ì›€ ê·¸ë¦¬ê³  ë‚¯ì„  ë¶€ë¶„ë„ ìˆì—ˆì§€ë§Œ ì‹ ê¸°í•˜ê³  ì¬ë¯¸ìˆê²Œ ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤.<br>
- name: Todo ì‚¬ì´íŠ¸
  color: color-4
  icon: icon-phone3
  content: ìƒˆë¡œìš´ í”„ë¡ íŠ¸ì—”ë“œ í”„ë ˆì„ì›Œí¬ì¸ Svelteì˜ ê¸°ë³¸ì ì¸ ê¸°ëŠ¥ë“¤ì„ ìµíˆê³  ê·¸ê²ƒì„ í™œìš©í•˜ì—¬ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤.
- name: ê°œì¸ ë¸”ë¡œê·¸ ì‚¬ì´íŠ¸
  color: color-5
  icon: icon-power
  content: Reactì˜ Next.jsë¥¼ í™œìš©í•˜ì—¬ ì •ì  ë¸”ë¡œê·¸ë¥¼ ë§Œë“¤ì—ˆìœ¼ë‚˜ Next.jsì˜ ì‚¬ìš©í•˜ëŠ” ë¶€ë¶„ì— ëŒ€í•´ ê³µë¶€í•˜ë©° ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤ 

exp_conters_bg_img: images/cover_bg_3.jpeg
exp_counters:
- name: Study Time
  count: 105
  speed: 10000
- name: project
  count: 5
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: ë™ì˜ëŒ€í•™êµ ì§€ì—­ì½œë¼ë³´ì„¼í„° ì¸í„´
  date: 2021.08~2021.12
  content: ë™ì˜ëŒ€í•™êµ ì§€ì—­ì½œë¼ë³´ì„¼í„°ì—ì„œ í•™ìƒë“¤ê³¼ ê° ì‹œì„¤ê³¼ì˜ í˜‘ì•½ì„ ë§ºì–´ ì§€ì—­ì‚¬íšŒë°œì „ì— ê¸°ì—¬í•˜ëŠ” ì¼ì„ í•˜ì˜€ìŠµë‹ˆë‹¤.
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft

- name: ì‚¼ê´‘ë©íŠ¸ë¦¬ ì „ì‚°íŒ€ ì¸í„´
  date: 2022.03~2022.05
  content: ì‚¼ê´‘ë©íŠ¸ë¦¬ ì „ì‚°íŒ€ì—ì„œ DelPhiê³¼ C#ë¥¼ í™œìš©í•˜ì—¬ í”„ë¡œê·¸ë¨ ê°œë°œ ë° ìœ ì§€ë³´ìˆ˜ ì‘ì—…ì„ í•˜ì˜€ìŠµë‹ˆë‹¤.
  color: color-2
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: DongEui-UNIVERSITY
  subtitle: ë™ì˜ëŒ€í•™êµ <br> ì»´í“¨í„°ì†Œí”„íŠ¸ì›¨ì–´ê³µí•™ê³¼ ì¡¸ì—…
  date: 2017.03 - 2021.02
  content: 2017ë…„ ì°½ì˜ì†Œí”„íŠ¸ì›¨ì–´ê³µí•™ë¶€ë¡œ ì…í•™í•˜ì˜€ìœ¼ë©° 2021ë…„ ì»´í“¨í„°ì†Œí”„íŠ¸ì›¨ì–´ê³µí•™ê³¼ë¡œ ì¡¸ì—…í•˜ì˜€ìŠµë‹ˆë‹¤
- title: Sungil Girl's High School
  subtitle: ì„±ì¼ì—¬ìê³ ë“±í•™êµ
  date: 2014.03 - 2017.02
  content: >-
    ì¸ë¬¸ê³„ ê³ ë“±í•™êµì¸ ì„±ì¼ì—¬ìê³ ë“±í•™êµë¥¼ 2014ë…„ì— ì…í•™í•˜ì˜€ìœ¼ë©° ì´ê³¼ê³„ì—´ë¡œ 2017ë…„ì— ì¡¸ì—…í•˜ì˜€ìŠµë‹ˆë‹¤.


# Blog
blog_meta: self-improvement
blog_header: BLOG 
blog_load_more: ë” ë°œì „í•˜ê¸° ìœ„í•´ í•­ìƒ ë…¸ë ¥í•©ë‹ˆë‹¤    # ë”ë³´ê¸° ë‚´ìš©
blog_load_more_url: #
blog_list:
- title: í¬ì› ë¸”ë¡œê·¸
  subtitle: ê°œë°œ ê³µë¶€ ë¸”ë¡œê·¸ 
  date: 2022.03
  content: í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ë©´ì„œ ê°œë…ì •ë¦¬ì™€ í”„ë¡œì íŠ¸ ê°œë°œ ì •ë¦¬ë¥¼ ìœ„í•œ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.
  thumbnail_url: images/blog2.jpg
  link: https://heewon528.tistory.com/
- title: ì‹ í¬ì› notion
  subtitle: ê°œë°œ ê³µë¶€ ë¸”ë¡œê·¸
  date: 2022.03
  content: ê°œì¸ì ì¸ ì¼ì • ì¡°ì •ê³¼ í”„ë¡œì íŠ¸ ê°œë°œ ì •ë¦¬, ê°œë… ì •ë¦¬ë¥¼ ìœ„í•œ Notion ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.
  thumbnail_url: images/blog1.jpg
  link: https://www.notion.so/SHINHEWON-b6a22e35be8d4699b09524273f4a55f3


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: hws4754@naver.com
  icon: icon-globe-outline
- title: ì„œìš¸ ê°•ë‚¨êµ¬ ê°œí¬ë™ 1236-20 
  icon: icon-map
- title: +82 10 4945 9474
  icon: icon-phone
- title: ì›¹ ì£¼ì†Œ
  icon: icon-layers2
  url: https://heewon528.tistory.com/
- title: GitHub ì£¼ì†Œ
  icon: icon-layers2
  url: https://github.com/shinheewon01
contact_message: <em>ì—°ë½í•´ì£¼ì…”ì„œ ê°ì‚¬í•©ë‹ˆë‹¤.</em> 24ì‹œê°„ì´ë‚´ì— íšŒì‹ ë“œë¦¬ë„ë¡ í•˜ê² ìŠµë‹ˆë‹¤. :)


optional_front_matter:
  remove_originals:    true
